Bug fixing crash when compile with !use_frameworks in Podfile
danielamitay/DAAppsViewController pull request #30
Opened 2016-05-19 18:34 UTC by rnaharro

I just created an UIImage category inside the DAAppViewCell.m file to handle the load of images from Main Bundle (compiled as static library) or Framework (compiled as framework).

This could close the #25 issue, created by @stsandro.

2016-08-22 06:26 UTC, coryalder commented
bump! just ran into this issue. :)

2017-12-04 10:44 UTC, ricsantos requested changes
Nice work, tested and works fine. Just that redundant nil check to fix.

2017-12-04 10:44 UTC, ricsantos commented on DAAppsViewController/DAAppViewCell.m
> +        if (!starsImageSheet) {
This nil check is redundant as it's taken care of in the category method `imageNamedFromMainBundleOrFramework` (assume it was accidentally left after refactoring).

2018-01-13 09:51 UTC, ricsantos commented on DAAppsViewController/DAAppViewCell.m
> +        image = [UIImage imageNamed:name inBundle:bundle compatibleWithTraitCollection:nil];
This is only available in iOS 8.0 or newer. This pod specifies min target of iOS 5.0 in the readme, but the podspec doesn't actually specify a min target.

2023-07-27 03:34 UTC, closed without merging